"""create learning and progress schema

Revision ID: ca6cf65dfb17
Revises:
Create Date: 2026-08-13 11:54:02.694737
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ca6cf65dfb17"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("source_language", sa.String(length=50), nullable=False),
        sa.Column("target_language", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_language", "target_language", name="uq_courses_language_pair"),
    )
    op.create_index(op.f("ix_courses_slug"), "courses", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("total_xp", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("weekly_xp", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("daily_xp", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("daily_goal", sa.Integer(), server_default=sa.text("(20)"), nullable=False),
        sa.Column("gems", sa.Integer(), server_default=sa.text("(500)"), nullable=False),
        sa.Column("hearts", sa.Integer(), server_default=sa.text("5"), nullable=False),
        sa.Column("max_hearts", sa.Integer(), server_default=sa.text("5"), nullable=False),
        sa.Column("last_heart_regenerated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_streak", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("longest_streak", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_activity_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("current_streak >= 0", name="ck_users_current_streak_nonnegative"),
        sa.CheckConstraint("daily_goal > 0", name="ck_users_daily_goal_positive"),
        sa.CheckConstraint("daily_xp >= 0", name="ck_users_daily_xp_nonnegative"),
        sa.CheckConstraint("gems >= 0", name="ck_users_gems_nonnegative"),
        sa.CheckConstraint("hearts >= 0 AND hearts <= max_hearts", name="ck_users_hearts_range"),
        sa.CheckConstraint("longest_streak >= current_streak", name="ck_users_streak_order"),
        sa.CheckConstraint("max_hearts > 0", name="ck_users_max_hearts_positive"),
        sa.CheckConstraint("total_xp >= 0", name="ck_users_total_xp_nonnegative"),
        sa.CheckConstraint("weekly_xp >= 0", name="ck_users_weekly_xp_nonnegative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position > 0", name="ck_units_position_positive"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "position", name="uq_units_course_position"),
    )
    op.create_index(op.f("ix_units_course_id"), "units", ["course_id"], unique=False)
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=50), server_default="star", nullable=False),
        sa.Column("color", sa.String(length=20), server_default="#58CC02", nullable=False),
        sa.Column("crown_goal", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position > 0", name="ck_skills_position_positive"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unit_id", "position", name="uq_skills_unit_position"),
    )
    op.create_index(op.f("ix_skills_unit_id"), "skills", ["unit_id"], unique=False)
    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("xp_reward", sa.Integer(), server_default=sa.text("(10)"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position > 0", name="ck_lessons_position_positive"),
        sa.CheckConstraint("xp_reward >= 0", name="ck_lessons_xp_reward_nonnegative"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_id", "position", name="uq_lessons_skill_position"),
    )
    op.create_index(op.f("ix_lessons_skill_id"), "lessons", ["skill_id"], unique=False)
    op.create_table(
        "user_skill_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("locked", "available", "completed", name="skill_status", native_enum=False),
            server_default="locked",
            nullable=False,
        ),
        sa.Column("progress_percent", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("crowns", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('locked', 'available', 'completed')", name="ck_user_skill_progress_status"
        ),
        sa.CheckConstraint("crowns >= 0", name="ck_user_skill_progress_crowns_nonnegative"),
        sa.CheckConstraint(
            "progress_percent >= 0 AND progress_percent <= 100",
            name="ck_user_skill_progress_percent_range",
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "skill_id", name="uq_user_skill_progress"),
    )
    op.create_index(
        op.f("ix_user_skill_progress_skill_id"), "user_skill_progress", ["skill_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_skill_progress_user_id"), "user_skill_progress", ["user_id"], unique=False
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "exercise_type",
            sa.Enum(
                "multiple_choice",
                "word_bank",
                "match_pairs",
                "fill_blank",
                "type_answer",
                name="exercise_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("instruction", sa.String(length=200), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "exercise_type IN "
            "('multiple_choice', 'word_bank', 'match_pairs', 'fill_blank', 'type_answer')",
            name="ck_exercises_type",
        ),
        sa.CheckConstraint("position > 0", name="ck_exercises_position_positive"),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id", "position", name="uq_exercises_lesson_position"),
    )
    op.create_index(op.f("ix_exercises_lesson_id"), "exercises", ["lesson_id"], unique=False)
    op.create_table(
        "lesson_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "in_progress",
                "completed",
                "failed",
                "abandoned",
                name="attempt_status",
                native_enum=False,
            ),
            server_default="in_progress",
            nullable=False,
        ),
        sa.Column(
            "current_exercise_position", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("correct_answers", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("incorrect_answers", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("hearts_lost", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("xp_earned", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('in_progress', 'completed', 'failed', 'abandoned')",
            name="ck_attempts_status",
        ),
        sa.CheckConstraint("correct_answers >= 0", name="ck_attempts_correct_nonnegative"),
        sa.CheckConstraint(
            "current_exercise_position >= 0", name="ck_attempts_position_nonnegative"
        ),
        sa.CheckConstraint("hearts_lost >= 0", name="ck_attempts_hearts_lost_nonnegative"),
        sa.CheckConstraint("incorrect_answers >= 0", name="ck_attempts_incorrect_nonnegative"),
        sa.CheckConstraint("xp_earned >= 0", name="ck_attempts_xp_earned_nonnegative"),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lesson_attempts_lesson_id"), "lesson_attempts", ["lesson_id"], unique=False
    )
    op.create_index(
        op.f("ix_lesson_attempts_user_id"), "lesson_attempts", ["user_id"], unique=False
    )
    op.create_table(
        "user_lesson_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("best_score", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("attempts_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "attempts_count >= 0", name="ck_user_lesson_progress_attempts_nonnegative"
        ),
        sa.CheckConstraint(
            "best_score >= 0 AND best_score <= 100", name="ck_user_lesson_progress_best_score_range"
        ),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "lesson_id", name="uq_user_lesson_progress"),
    )
    op.create_index(
        op.f("ix_user_lesson_progress_lesson_id"),
        "user_lesson_progress",
        ["lesson_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_lesson_progress_user_id"), "user_lesson_progress", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_lesson_progress_user_id"), table_name="user_lesson_progress")
    op.drop_index(op.f("ix_user_lesson_progress_lesson_id"), table_name="user_lesson_progress")
    op.drop_table("user_lesson_progress")
    op.drop_index(op.f("ix_lesson_attempts_user_id"), table_name="lesson_attempts")
    op.drop_index(op.f("ix_lesson_attempts_lesson_id"), table_name="lesson_attempts")
    op.drop_table("lesson_attempts")
    op.drop_index(op.f("ix_exercises_lesson_id"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(op.f("ix_user_skill_progress_user_id"), table_name="user_skill_progress")
    op.drop_index(op.f("ix_user_skill_progress_skill_id"), table_name="user_skill_progress")
    op.drop_table("user_skill_progress")
    op.drop_index(op.f("ix_lessons_skill_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_skills_unit_id"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_units_course_id"), table_name="units")
    op.drop_table("units")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_courses_slug"), table_name="courses")
    op.drop_table("courses")
    # ### end Alembic commands ###
